version: '2'
services:
    db:
        image: mysql:5.7.17
        ports:
          - "3306:3306"
        env_file:
          - .env
        volumes:
          - "../volumes/mysql/dev:/var/lib/mysql"
        networks:
          crv_dev_network:
            aliases:
              - mysql
    nginx:
        image: codereviewvideos/nginx.dev
        ports:
          - "81:80"
        restart: always
        volumes:
          - "../volumes/nginx/logs:/var/log/nginx/"
        volumes_from:
            - php
        networks:
          crv_dev_network:
            aliases:
              - nginx
    php:
        image: codereviewvideos/www.dev
        restart: always
        env_file:
          - .env
        volumes:
          - "../volumes/php/app/cache:/var/www/dev/app/cache/:rw"
          - "../volumes/php/app/logs:/var/www/dev/app/logs/:rw"
          - "../volumes/.composer:/var/www/.composer"
          - "../app:/var/www/dev"
        networks:
          crv_dev_network:
            aliases:
              - php
networks:
  crv_dev_network:
    driver: bridge
