version: '2'
services:
    db:
        image: mysql:5.7.17
        ports:
          - "3306:3306"
        env_file:
          - .env
        volumes:
          - "db:/var/lib/mysql"
        networks:
          crv_dev_network:
            aliases:
              - mysql
    nginx:
        image: codereviewvideos/nginx.dev
        ports:
          - "81:80"
        restart: always
        volumes_from:
            - php
        networks:
          crv_dev_network:
            aliases:
              - nginx
    php:
        image: codereviewvideos/www.dev
        restart: always
        env_file:
          - .env
        volumes:
          - "../app:/var/www/dev"
        networks:
          crv_dev_network:
            aliases:
              - php
networks:
  crv_dev_network:
    driver: bridge

volumes:
  db:
