<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive()
    {
        return $this
                ->createQueryBuilder('news')
                ->where('news.active = :active')
                ->setParameter('active', 1)
                ->getQuery()
                ->getResult();
    }
}
